server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/identity_service'
    username: '${MYSQL_USER:root}'
    password: '${MYSQL_PASSWORD}'

